name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
            make: make
          - os: macos-13
            cc: clang
            make: make
          - os: macos-14
            cc: clang
            make: make
          - os: windows-latest
            cc: gcc
            make: mingw32-make

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build and test
        shell: bash
        run: |
          ${{ matrix.make }} test CC=${{ matrix.cc }}
